spring:
  # H2 콘솔 설정
  h2:
    console:
      enabled: true            # H2 콘솔 사용 여부
      path: /h2-console        # 접근 주소 (기본값: /h2-console)
  # 데이터 설정
  datasource:
    driver-class-name: org.h2.Driver
    # 인메모리 방식 (애플리케이션 종료 시 데이터 삭제)
    url: jdbc:h2:mem:testdb
    # 로컬 파일 방식 (데이터 보존 시 사용 예: jdbc:h2:file:~/testdb)
    username: sa
    password:
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create         # 시작 시 테이블 생성
    show-sql: true             # 실행 쿼리 출력
    properties:
      hibernate:
        format_sql: true       # 쿼리 포멧팅